# Generated by Django 2.2.2 on 2019-06-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190615_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
