# Generated by Django 2.2.2 on 2019-06-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_address_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_id',
        ),
    ]
